# Generated by Django 4.0.1 on 2022-02-09 19:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('is_active', models.CharField(default='y', max_length=1)),
            ],
            options={
                'db_table': 'books',
            },
            managers=[
                ('active_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
