# Generated by Django 4.0.1 on 2022-02-11 15:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'emp',
            },
        ),
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('active_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
    ]
